{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"df_processed\",\"Errores en df_processed\",\"df_processed1\",\"Sheet1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-CO",
    "cultures": [
      {
        "name": "es-CO",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errores en df_processed",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Origen = df_processed,",
          "  #\"Errores de coincidencia detectados\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Origen, Table.ColumnsOfType(Origen, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"El tipo del valor no coincide con el tipo de la columna.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Origen, pairs),",
          "  #\"Índice agregado\" = Table.AddIndexColumn(#\"Errores de coincidencia detectados\", \"Número de fila\" ,1),",
          "  #\"Conservar errores\" = Table.SelectRowsWithErrors(#\"Índice agregado\", {\"Unnamed: 0\", \"country\", \"description\", \"designation\", \"points\", \"price\", \"province\", \"region_1\", \"region_2\", \"taster_name\", \"taster_twitter_handle\", \"title\", \"variety\", \"winery\", \"Cleaned_Tweet\", \"Processed_Tweet\", \"target\"}),",
          "  #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Conservar errores\", {\"Número de fila\", \"Unnamed: 0\", \"country\", \"description\", \"designation\", \"points\", \"price\", \"province\", \"region_1\", \"region_2\", \"taster_name\", \"taster_twitter_handle\", \"title\", \"variety\", \"winery\", \"Cleaned_Tweet\", \"Processed_Tweet\", \"target\"}),",
          "    #\"Errores quitados\" = Table.RemoveRowsWithErrors(#\"Columnas reordenadas\")",
          "in",
          "  #\"Errores quitados\""
        ],
        "kind": "m",
        "lineageTag": "88359701-67f6-4afd-b4a1-9076a0baebbb",
        "queryGroup": "Errores en las consultas: 21/08/2024 2:23:46 p  m"
      },
      {
        "name": "df_processed",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = Csv.Document(File.Contents(\"C:\\Users\\manue\\Downloads\\df_processed.csv\"),[Delimiter=\",\", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Unnamed: 0\", Int64.Type}, {\"country\", type text}, {\"description\", type text}, {\"designation\", type text}, {\"points\", Int64.Type}, {\"price\", Int64.Type}, {\"province\", type text}, {\"region_1\", type text}, {\"region_2\", type text}, {\"taster_name\", type text}, {\"taster_twitter_handle\", type text}, {\"title\", type text}, {\"variety\", type text}, {\"winery\", type text}, {\"Cleaned_Tweet\", type text}, {\"Processed_Tweet\", type text}, {\"target\", type text}}),",
          "    #\"Filas filtradas\" = Table.SelectRows(#\"Tipo cambiado\", each ([target] = \"\")),",
          "    #\"Errores quitados\" = Table.RemoveRowsWithErrors(#\"Filas filtradas\"),",
          "    #\"Filas inferiores quitadas\" = Table.RemoveLastN(#\"Errores quitados\",1),",
          "    #\"Filas superiores quitadas\" = Table.Skip(#\"Filas inferiores quitadas\",22),",
          "    #\"Filas filtradas1\" = Table.SelectRows(#\"Filas superiores quitadas\", each true)",
          "in",
          "    #\"Filas filtradas1\""
        ],
        "kind": "m",
        "lineageTag": "76c51ef2-b146-4350-a2e0-71659c91084f"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errores en las consultas cargadas en 21/08/2024 2:23:46 p. m..",
        "folder": "Errores en las consultas: 21/08/2024 2:23:46 p  m"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_11ae0194-073e-42f0-bf73-6b474e86b151",
        "fromColumn": "Opinión",
        "fromTable": "df_processed1",
        "toColumn": "Opinión",
        "toTable": "Sheet1"
      }
    ],
    "sourceQueryCulture": "es-CO",
    "tables": [
      {
        "name": "DateTableTemplate_70a2fc19-f1db-4fd4-b280-4e83f3462812",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fa3daebd-ef45-4de9-aac7-b957778440d8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7d4cb418-7d39-4180-a335-06f0f6e0c03e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e4fa4080-4522-4bcc-ade9-e0baf9f2d2aa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "197ea8c6-ff39-4d79-ba04-36f3920acf8f",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "74a78b11-1565-449a-bd8b-63963ff13b8e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "f9249bf4-ac09-4660-863c-3f5311d9d4f5",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "14a0601a-968e-4af3-846a-477768a3176b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "fc102ef9-2860-4491-a088-ceffedf59cc3",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "fb7b0710-8565-4e34-8316-7db850314839",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "1d2c99b2-4a5d-4f89-ab99-e8c9ff4ca654",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "eb79928b-89ea-4c05-b2e8-7bb512749aa4",
                "ordinal": 3
              }
            ],
            "lineageTag": "96d3bbb0-a2e8-4cef-b742-d551740fbba9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b5275957-44fe-436a-aad7-bab4e86025a2",
        "partitions": [
          {
            "name": "DateTableTemplate_70a2fc19-f1db-4fd4-b280-4e83f3462812",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "df_processed1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Unnamed: 0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06e484af-068a-41bb-a26b-886f4844bb4d",
            "sourceColumn": "Unnamed: 0",
            "summarizeBy": "sum"
          },
          {
            "name": "País de origen del vino",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f5a87f1-469d-4712-89ad-0f615d0c5274",
            "sourceColumn": "País de origen del vino",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56454d05-77c8-44e3-a4db-27689903145a",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "designation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e487c22-4356-4fbe-b06e-e5548f74a987",
            "sourceColumn": "designation",
            "summarizeBy": "none"
          },
          {
            "name": "Puntaje del vino",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ff55d50-5cba-4c61-8f1a-46cf5d615199",
            "sourceColumn": "Puntaje del vino",
            "summarizeBy": "none"
          },
          {
            "name": "Precio del vino($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70a28c4b-63b2-427e-91cd-a5940257c976",
            "sourceColumn": "Precio del vino($)",
            "summarizeBy": "none"
          },
          {
            "name": "province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28f3f2f4-d8c1-4178-8ac7-ae4e5fa1b9a1",
            "sourceColumn": "province",
            "summarizeBy": "none"
          },
          {
            "name": "region_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c9e44be-3e50-4793-8335-637f4f5d4c64",
            "sourceColumn": "region_1",
            "summarizeBy": "none"
          },
          {
            "name": "region_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a411fdf0-812f-44ea-864a-6e3271a2d533",
            "sourceColumn": "region_2",
            "summarizeBy": "none"
          },
          {
            "name": "taster_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a2db277-647b-43e1-b238-aeb981da9dac",
            "sourceColumn": "taster_name",
            "summarizeBy": "none"
          },
          {
            "name": "taster_twitter_handle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a81616e-015d-4384-aaf0-7247b873f9b9",
            "sourceColumn": "taster_twitter_handle",
            "summarizeBy": "none"
          },
          {
            "name": "title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45c2bcf3-7f95-4fa8-bb7f-99fe3056ef08",
            "sourceColumn": "title",
            "summarizeBy": "none"
          },
          {
            "name": "Variedad de vino",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e314399-67d9-4715-810f-2ba0a3e0c1a5",
            "sourceColumn": "Variedad de vino",
            "summarizeBy": "none"
          },
          {
            "name": "winery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "830efacf-e7a7-41a8-b43f-e5df9bc07da1",
            "sourceColumn": "winery",
            "summarizeBy": "none"
          },
          {
            "name": "Cleaned_Tweet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ef71cb7-79a3-42a3-90d4-daa65007c0a6",
            "sourceColumn": "Cleaned_Tweet",
            "summarizeBy": "none"
          },
          {
            "name": "Processed_Tweet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d02a8abb-312c-42c3-a111-e40ae87bf4ba",
            "sourceColumn": "Processed_Tweet",
            "summarizeBy": "none"
          },
          {
            "name": "Opinión",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fad0a7a-3276-49ea-b747-4d9d97060e6b",
            "sourceColumn": "Opinión",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6cba534b-1e58-4e1b-a37d-88bcf037da36",
        "partitions": [
          {
            "name": "df_processed1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\manue\\Desktop\\datavios.xlsx\"), null, true),",
                "    df_processed_Table = Origen{[Item=\"df_processed\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(df_processed_Table,{{\"Unnamed: 0\", Int64.Type}, {\"country\", type text}, {\"description\", type text}, {\"designation\", type text}, {\"points\", Int64.Type}, {\"price\", Int64.Type}, {\"province\", type text}, {\"region_1\", type text}, {\"region_2\", type text}, {\"taster_name\", type text}, {\"taster_twitter_handle\", type text}, {\"title\", type text}, {\"variety\", type text}, {\"winery\", type text}, {\"Cleaned_Tweet\", type text}, {\"Processed_Tweet\", type text}, {\"target\", type text}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Tipo cambiado\",{{\"target\", \"Opinión\"}, {\"country\", \"País de origen del vino\"}, {\"variety\", \"Variedad de vino\"}, {\"price\", \"Precio del vino($)\"}, {\"points\", \"Puntaje del vino\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sheet1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Opinión",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4164146-96cb-4ba8-ae9c-b1dafd519c8e",
            "sourceColumn": "Opinión",
            "summarizeBy": "none"
          },
          {
            "name": "conteo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "7aee44a6-43af-4c73-b7e1-634ca77787c6",
            "sourceColumn": "conteo",
            "summarizeBy": "none"
          },
          {
            "name": "%/sentimiento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c23b2ef9-d3b8-4725-ac98-8d94f9a15bcf",
            "sourceColumn": "%/sentimiento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "12453fb5-c4f9-4565-9fcc-6233a2fb6248",
        "partitions": [
          {
            "name": "Sheet1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\manue\\Documents\\vino.xlsx\"), null, true),",
                "    Sheet1_Sheet = Origen{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Opinión\", type text}, {\"conteo\", Int64.Type}}),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Tipo cambiado\",{{\"conteo\", type number}, {\"porcentaje\", Percentage.Type}}),",
                "    #\"Tipo cambiado2\" = Table.TransformColumnTypes(#\"Tipo cambiado1\",{{\"porcentaje\", type number}}),",
                "    #\"Primeros caracteres extraídos\" = Table.TransformColumns(#\"Tipo cambiado2\", {{\"porcentaje\", each Text.Start(Text.From(_, \"es-CO\"), 4), type text}}),",
                "    #\"Primeros caracteres extraídos1\" = Table.TransformColumns(#\"Primeros caracteres extraídos\", {{\"porcentaje\", each Text.Start(_, 5), type text}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Primeros caracteres extraídos1\",{{\"porcentaje\", \"Porcentaje/sentimiento\"}}),",
                "    #\"Filas en blanco eliminadas\" = Table.SelectRows(#\"Columnas con nombre cambiado\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Errores quitados\" = Table.RemoveRowsWithErrors(#\"Filas en blanco eliminadas\"),",
                "    #\"Columnas con nombre cambiado1\" = Table.RenameColumns(#\"Errores quitados\",{{\"Porcentaje/sentimiento\", \"%/sentimiento\"}})",
                "in",
                "    #\"Columnas con nombre cambiado1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}